import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/component/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden">
        <Header /> {/* Header should be independent */}
        {children} {/* Render children outside of Header */}
      </body>
    </html>
  );
}